# Put your seeding script here

poll_attributes = [{:featured            => true, 
                    :vanity              => true,
                    :reveal_results      => true,
                    :enabled             => true,
                    :question_attributes => {:body => "Who is going to win the World Series?",
                                             :question_options_attributes => [{:response_value => "St. Louis Cardinals"},
                                                                              {:response_value => "Boston Red Sox"}]}},
                   {:featured            => true, 
                    :vanity              => true,
                    :reveal_results      => true,
                    :enabled             => true,
                    :question_attributes => {:body => "Which email service provider is the least cool?",
                                             :question_options_attributes => [{:response_value => "@yahoo.com"},
                                                                              {:response_value => "@hotmail.com"},
                                                                              {:response_value => "@msn.com"},
                                                                              {:response_value => "@prodigy.com"},
                                                                              {:response_value => "@gmail.com"},
                                                                              {:response_value => "@aol.com"}]}},                                                                              
                   {:featured            => true, 
                    :vanity              => true,
                    :reveal_results      => true,
                    :enabled             => true,
                    :question_attributes => {:body => "Who is going to win in week 8 of the NFL?",
                                             :question_options_attributes => [{:response_value => "Panthers"},
                                                                              {:response_value => "Buccaneers"}]}},
                   {:featured            => true, 
                    :vanity              => true,
                    :reveal_results      => true,
                    :enabled             => true,
                    :question_attributes => {:body => "How much money is enough?",
                                             :question_options_attributes => [{:response_value => "$1k"},
                                                                              {:response_value => "$10k"},
                                                                              {:response_value => "$100k"},
                                                                              {:response_value => "$1 mill."},
                                                                              {:response_value => "$1 bill."},
                                                                              {:response_value => "No such thing"}]}},
                                                                              
                   {:featured            => true, 
                    :vanity              => true,
                    :reveal_results      => true,
                    :enabled             => true,
                    :question_attributes => {:body => "Who is going to win in week 8 of the NFL?",
                                             :question_options_attributes => [{:response_value => "Bills"},
                                                                              {:response_value => "Saints"}]}},
                   {:featured            => true, 
                    :vanity              => true,
                    :reveal_results      => true,
                    :enabled             => true,
                    :question_attributes => {:body => "What is your operating system of choice?",
                                             :question_options_attributes => [{:response_value => "Mac OS"},
                                                                              {:response_value => "Windows"},
                                                                              {:response_value => "Linux"}]}},
                                                                              
                   {:featured            => true, 
                    :vanity              => true,
                    :reveal_results      => true,
                    :enabled             => true,
                    :question_attributes => {:body => "Who is going to win in week 8 of the NFL?",
                                             :question_options_attributes => [{:response_value => "Browns"},
                                                                              {:response_value => "Chiefs"}]}},
                   {:featured            => true, 
                    :vanity              => true,
                    :reveal_results      => true,
                    :enabled             => true,
                    :question_attributes => {:body => "Which genre of music do you like the best?",
                                             :question_options_attributes => [{:response_value => "Blues"},
                                                                              {:response_value => "Jazz"},
                                                                              {:response_value => "Pop"},
                                                                              {:response_value => "Rock 'n' Roll"},
                                                                              {:response_value => "Rhythm and Blues"},
                                                                              {:response_value => "Metal"},
                                                                              {:response_value => "Funk"},
                                                                              {:response_value => "Dance"}]}},
                                                                              
                   {:featured            => true, 
                    :vanity              => true,
                    :reveal_results      => true,
                    :enabled             => true,
                    :question_attributes => {:body => "Who is going to win in week 8 of the NFL?",
                                             :question_options_attributes => [{:response_value => "Cowboys"},
                                                                              {:response_value => "Lions"}]}},
                   {:featured            => true, 
                    :vanity              => true,
                    :reveal_results      => true,
                    :enabled             => true,
                    :question_attributes => {:body => "What's your favorite source control management system?",
                                             :question_options_attributes => [{:response_value => "cvs"},
                                                                              {:response_value => "git"},
                                                                              {:response_value => "svn"},
                                                                              {:response_value => "mercurial"},
                                                                              {:response_value => "perforce"}                                                                              
                                                                              ]}},

                   {:featured            => true, 
                    :vanity              => true,
                    :reveal_results      => true,
                    :enabled             => true,
                    :question_attributes => {:body => "Who is going to win in week 8 of the NFL?",
                                             :question_options_attributes => [{:response_value => "49ers"},
                                                                              {:response_value => "Jaguars"}]}},
                   {:featured            => true, 
                    :vanity              => true,
                    :reveal_results      => true,
                    :enabled             => true,
                    :question_attributes => {:body => "Where would you prefer to live?",
                                             :question_options_attributes => [{:response_value => "Big city"},
                                                                              {:response_value => "Small town"}]}},
                                                                              
                   {:featured            => true, 
                    :vanity              => true,
                    :reveal_results      => true,
                    :enabled             => true,
                    :question_attributes => {:body => "Who is going to win in week 8 of the NFL?",
                                             :question_options_attributes => [{:response_value => "Dolphins"},
                                                                              {:response_value => "Patriots"}]}},
                   {:featured            => true, 
                    :vanity              => true,
                    :reveal_results      => true,
                    :enabled             => true,
                    :question_attributes => {:body => "What type of database system?",
                                             :question_options_attributes => [{:response_value => "Relational DB"},
                                                                              {:response_value => "NoSQL"}]}},
                   {:featured            => true, 
                    :vanity              => true,
                    :reveal_results      => true,
                    :enabled             => true,
                    :question_attributes => {:body => "Which web browser runs your life?",
                                             :question_options_attributes => [{:response_value => "Chrome"},
                                                                              {:response_value => "Safari"},
                                                                              {:response_value => "Internet Explorer"},
                                                                              {:response_value => "AOL"}
                                                                              ]}},
                   {:featured            => true, 
                    :vanity              => true,
                    :reveal_results      => true,
                    :enabled             => true,
                    :question_attributes => {:body => "Who is going to win in week 8 of the NFL?",
                                             :question_options_attributes => [{:response_value => "Giants"},
                                                                              {:response_value => "Eagles"}]}},
                   {:featured            => true, 
                    :vanity              => true,
                    :reveal_results      => true,
                    :enabled             => true,
                    :question_attributes => {:body => "Who is going to win in week 8 of the NFL?",
                                             :question_options_attributes => [{:response_value => "Jets"},
                                                                              {:response_value => "Bengals"}]}},
                   {:featured            => true, 
                    :vanity              => true,
                    :reveal_results      => true,
                    :enabled             => true,
                    :question_attributes => {:body => "What is your favorite writing tool?",
                                             :question_options_attributes => [{:response_value => "vi"},
                                                                              {:response_value => "emacs"},
                                                                              {:response_value => "pen"},
                                                                              {:response_value => "pencil"},
                                                                              {:response_value => "stylus"}]}},
                                                                              
                   {:featured            => true, 
                    :vanity              => true,
                    :reveal_results      => true,
                    :enabled             => true,
                    :question_attributes => {:body => "Who is going to win in week 8 of the NFL?",
                                             :question_options_attributes => [{:response_value => "Steelers"},
                                                                              {:response_value => "Raiders"}]}},
                   {:featured            => true, 
                    :vanity              => true,
                    :reveal_results      => true,
                    :enabled             => true,
                    :question_attributes => {:body => "Photo is your favorite photo sharing site?",
                                             :question_options_attributes => [{:response_value => "Flickr"},
                                                                              {:response_value => "Instagram"},
                                                                              {:response_value => "Snapfish"},
                                                                              {:response_value => "Photobucket"}]}},                                                           
                                                                              
                   {:featured            => true, 
                    :vanity              => true,
                    :reveal_results      => true,
                    :enabled             => true,
                    :question_attributes => {:body => "Who is going to win in week 8 of the NFL?",
                                             :question_options_attributes => [{:response_value => "Redskins"},
                                                                              {:response_value => "Broncos"}]}},
                   {:featured            => true, 
                    :vanity              => true,
                    :reveal_results      => true,
                    :enabled             => true,
                    :question_attributes => {:body => "Who is going to win in week 8 of the NFL?",
                                             :question_options_attributes => [{:response_value => "Falcons"},
                                                                              {:response_value => "Cardinals"}]}},
                   {:featured            => true, 
                    :vanity              => true,
                    :reveal_results      => true,
                    :enabled             => true,
                    :question_attributes => {:body => "What is your mobile platform of choice?",
                                             :question_options_attributes => [{:response_value => "iOS"},
                                                                              {:response_value => "Android"},
                                                                              {:response_value => "Windows"},
                                                                              {:response_value => "Blackberry"},
                                                                              {:response_value => "WebOS"}]}},
                                                                              
                   {:featured            => true, 
                    :vanity              => true,
                    :reveal_results      => true,
                    :enabled             => true,
                    :question_attributes => {:body => "Who is going to win in week 8 of the NFL?",
                                             :question_options_attributes => [{:response_value => "Packers"},
                                                                              {:response_value => "Vikings"}]}},
                   {:featured            => true, 
                    :vanity              => true,
                    :reveal_results      => true,
                    :enabled             => true,
                    :question_attributes => {:body => "What of these languages do you prefer the most?",
                                             :question_options_attributes => [{:response_value => "Ruby"},
                                                                              {:response_value => "Python"},
                                                                              {:response_value => "Objective-C"},
                                                                              {:response_value => "C#"},
                                                                              {:response_value => "C/C++"},
                                                                              {:response_value => "Clojure"},
                                                                              {:response_value => "Java"},
                                                                              {:response_value => "PHP"}]}},

                   {:featured            => true, 
                    :vanity              => true,
                    :reveal_results      => true,
                    :enabled             => true,
                    :question_attributes => {:body => "Who is going to win in week 8 of the NFL?",
                                             :question_options_attributes => [{:response_value => "Seahawks"},
                                                                              {:response_value => "Rams"}]}}

                  ]

users = User.order(:id).limit(5)

poll_attributes.each do |poll|
  users[rand(5)].polls.create!(poll)
end
