development:
  adapter: mysql2
  encoding: utf8
  database: pollse_development
  username: root
  password: 
  host: 127.0.0.1
  port: 3306

test:
  adapter: mysql2
  encoding: utf8
  database: pollse_test
  username: root
  password: 
  host: 127.0.0.1
  port: 3306

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: railsrumble_production
  pool: 5
  username: root
  password: "qT2W1db7h5ecUspxlBEy"
  host: localhost
  socket: /var/run/mysqld/mysqld.sock
